# Generated by Django 5.2.10 on 2026-04-13 17:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_activity_lead_task_deal"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lead",
            name="source",
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
