# Generated by Django 5.2.10 on 2026-04-14 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_deal_created_at_lead_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="assigned_to",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lead",
            name="interest",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
