# Generated by Django 5.2.10 on 2026-04-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_lead_assigned_to_lead_interest"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="status",
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
