# Generated by Django 5.2.10 on 2026-04-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_leadnote"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="priority",
            field=models.CharField(
                choices=[("HOT", "Hot"), ("WARM", "Warm"), ("COLD", "Cold")],
                default="WARM",
                max_length=10,
            ),
        ),
    ]
