# Generated by Django 5.2.10 on 2026-04-14 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_lead_priority"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="documents/")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("LEGAL", "Legal"),
                            ("SALES", "Sales"),
                            ("PROPERTY", "Property"),
                            ("PERSONAL", "Personal"),
                        ],
                        max_length=20,
                    ),
                ),
                ("size", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
