# Generated by Django 5.2.10 on 2026-04-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_remove_task_completed_remove_task_due_date_task_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
