# Generated by Django 5.2.10 on 2026-04-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_task_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("lead", "Lead"),
                            ("message", "Message"),
                            ("task", "Task"),
                            ("document", "Document"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
