# Generated by Django 5.2.10 on 2026-04-14 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="agent",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to="core.agent"
            ),
            preserve_default=False,
        ),
    ]
