# Generated by Django 5.2.10 on 2026-04-14 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_aiinsight_campaign_leadscore"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="conversion",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="campaign",
            name="reach",
            field=models.IntegerField(default=0),
        ),
    ]
