# Generated by Django 5.2.10 on 2026-04-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_campaign_conversion_campaign_reach"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="campaigns/"),
        ),
    ]
