# Generated by Django 5.2.10 on 2026-04-14 21:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_campaign_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="agent",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="role",
            field=models.CharField(default="Agent", max_length=50),
        ),
    ]
