# Generated by Django 5.2.10 on 2026-04-15 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_agent_builder_lead_builder_alter_agent_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="last_contacted",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="lead",
            name="assigned_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leads",
                to="core.agent",
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="status",
            field=models.CharField(
                choices=[("HOT", "Hot"), ("WARM", "Warm"), ("COLD", "Cold")],
                max_length=20,
            ),
        ),
    ]
