# Generated by Django 5.2.10 on 2026-04-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_lead_last_contacted_lead_notes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lead",
            name="agent",
        ),
        migrations.AlterField(
            model_name="lead",
            name="properties",
            field=models.ManyToManyField(
                blank=True, related_name="interested_leads", to="core.property"
            ),
        ),
    ]
