# Generated by Django 5.2.10 on 2026-04-15 11:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_remove_lead_agent_alter_lead_properties"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitevisit",
            name="agent",
        ),
        migrations.RemoveField(
            model_name="sitevisit",
            name="date",
        ),
        migrations.RemoveField(
            model_name="sitevisit",
            name="lead",
        ),
        migrations.RemoveField(
            model_name="sitevisit",
            name="time",
        ),
        migrations.AddField(
            model_name="sitevisit",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sitevisit",
            name="status",
            field=models.CharField(
                choices=[
                    ("SCHEDULED", "Scheduled"),
                    ("DONE", "Done"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="SCHEDULED",
                max_length=20,
            ),
        ),
    ]
