# Generated by Django 5.2.10 on 2026-04-15 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_remove_sitevisit_agent_remove_sitevisit_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitevisit",
            name="agent",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visits",
                to="core.agent",
            ),
            preserve_default=False,
        ),
    ]
