# Generated by Django 5.2.10 on 2026-04-17 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_sitevisit_date_sitevisit_lead_sitevisit_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="user",
        ),
        migrations.AddField(
            model_name="property",
            name="builder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="properties",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
