# Generated by Django 5.2.10 on 2026-04-17 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_remove_property_user_property_builder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leads",
                to="core.agent",
            ),
        ),
    ]
