# Generated by Django 5.2.10 on 2026-04-17 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_user_profile_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="profile_image",
        ),
    ]
