# Generated by Django 5.2.10 on 2026-04-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_user_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyimage",
            name="image",
            field=models.ImageField(upload_to="property_gallery/"),
        ),
    ]
