# Generated by Django 5.2.10 on 2026-04-24 16:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_alter_propertyimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="thumbnail",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="propertyimage",
            name="image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image"
            ),
        ),
    ]
