# Generated by Django 5.2.10 on 2026-04-30 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_alter_property_thumbnail_alter_propertyimage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="amenities",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name="PropertyAmenity",
        ),
    ]
