# Generated by Django 5.2.10 on 2026-05-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_property_amenities_delete_propertyamenity"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="brochure",
            field=models.FileField(blank=True, null=True, upload_to="brochures/"),
        ),
        migrations.AddField(
            model_name="property",
            name="configuration",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="highlights",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="map_link",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="possession_date",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="rera_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
