# Generated by Django 5.2.10 on 2026-05-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_property_brochure_property_configuration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquiry",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
