# Generated by Django 5.2.10 on 2026-05-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_inquiry_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="nearby_places",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
