# Generated by Django 5.2.10 on 2026-05-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_task_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
