# Generated by Django 5.2.10 on 2026-05-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_alter_agent_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="possession",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
