# Generated by Django 5.2.10 on 2026-05-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_property_possession"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="beds",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="possession",
            field=models.CharField(
                blank=True, default="Ready to Move", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("Flat", "Flat"),
                    ("Villa", "Villa"),
                    ("Bungalow", "Bungalow"),
                    ("Duplex", "Duplex"),
                    ("Penthouse", "Penthouse"),
                    ("Office", "Office"),
                    ("Shop", "Shop"),
                    ("Showroom", "Showroom"),
                    ("Warehouse", "Warehouse"),
                    ("Land", "Land"),
                    ("Plot", "Plot"),
                    ("Plots", "Plots"),
                    ("Farmhouse", "Farmhouse"),
                    ("Industrial", "Industrial"),
                ],
                default="Flat",
                max_length=50,
            ),
        ),
    ]
