# Generated by Django 5.2.10 on 2026-05-24 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_alter_property_beds_alter_property_possession_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="builder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("NEGOTIATION", "Negotiation"),
                    ("BOOKED", "Booked"),
                    ("CLOSED", "Closed"),
                    ("FAILED", "Failed"),
                ],
                default="NEW",
                max_length=20,
            ),
        ),
    ]
