# Generated by Django 5.2.10 on 2026-05-26 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_followup_leadactivity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="followup",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="followup",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("DONE", "Done"),
                    ("MISSED", "Missed"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
    ]
