# Generated by Django 5.2.10 on 2026-05-26 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_alter_followup_note_alter_followup_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="lead",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deals",
                to="core.lead",
            ),
        ),
    ]
