# Generated by Django 5.2.10 on 2026-05-27 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_deal_lead"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="project_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
