# Generated by Django 5.2.10 on 2026-06-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_property_land_parcel_property_launch_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="builder_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
