# Generated by Django 5.2.10 on 2026-06-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_property_builder_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="max_price",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="price",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="starting_price",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
