# Generated by Django 5.2.10 on 2026-06-07 12:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0049_alter_property_max_price_alter_property_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agent",
            name="builder",
        ),
        migrations.AddField(
            model_name="agent",
            name="builders",
            field=models.ManyToManyField(
                blank=True, related_name="builder_agents", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
