# Generated by Django 5.2.10 on 2026-06-08 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_remove_agent_builder_agent_builders"),
    ]

    operations = [
        migrations.AddField(
            model_name="followup",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="followup",
            name="is_auto_created",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="followup",
            name="sequence_step",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="lead",
            name="automation_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="escalation_level",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="lead",
            name="followup_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="lead",
            name="last_followup_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="followup",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("DONE", "Done"),
                    ("MISSED", "Missed"),
                    ("ESCALATED", "Escalated"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="AutomationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("SMS_SENT", "SMS Sent"),
                            ("EMAIL_SENT", "Email Sent"),
                            ("WHATSAPP_SENT", "WhatsApp Sent"),
                            ("MISSED_FOLLOWUP", "Missed Followup"),
                            ("ESCALATION", "Escalation"),
                            ("AUTO_MESSAGE", "Auto Message"),
                        ],
                        max_length=50,
                    ),
                ),
                ("channel", models.CharField(blank=True, max_length=20, null=True)),
                ("message", models.TextField()),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="SENT", max_length=20)),
                ("response", models.TextField(blank=True, null=True)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_logs",
                        to="core.lead",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EscalationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("missed_followups", models.IntegerField(default=2)),
                ("auto_reassign", models.BooleanField(default=True)),
                (
                    "notify_channels",
                    models.CharField(default="EMAIL,WHATSAPP", max_length=100),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "builder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escalation_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "escalate_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escalated_leads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DripSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("step_number", models.IntegerField()),
                ("delay_days", models.IntegerField()),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("SMS", "SMS"),
                            ("EMAIL", "Email"),
                            ("WHATSAPP", "WhatsApp"),
                        ],
                        max_length=20,
                    ),
                ),
                ("template_message", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "builder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drip_sequences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["step_number"],
                "unique_together": {("builder", "step_number")},
            },
        ),
    ]
