# Generated by Django 5.2.10 on 2026-06-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_wishlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="sales_head_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
