# Generated by Django 5.2.10 on 2026-06-16 04:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0053_property_sales_head_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("EXPORT", "Export"),
                            ("IMPORT", "Import"),
                            ("VIEW", "View"),
                        ],
                        max_length=20,
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("object_id", models.CharField(max_length=100)),
                ("object_repr", models.CharField(max_length=255)),
                ("changes", models.JSONField(default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="PropertyInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inquiry_date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INTERESTED", "Interested"),
                            ("VISITED", "Visited"),
                            ("NEGOTIATING", "Negotiating"),
                            ("BOOKED", "Booked"),
                            ("NOT_INTERESTED", "Not Interested"),
                        ],
                        default="INTERESTED",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-inquiry_date"],
            },
        ),
        migrations.CreateModel(
            name="SavedProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("price_monthly", models.DecimalField(decimal_places=2, max_digits=10)),
                ("price_yearly", models.DecimalField(decimal_places=2, max_digits=10)),
                ("max_properties", models.PositiveIntegerField(default=10)),
                ("max_agents", models.PositiveIntegerField(default=5)),
                ("max_leads", models.PositiveIntegerField(default=100)),
                ("features", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["price_monthly"],
            },
        ),
        migrations.CreateModel(
            name="UserSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("auto_renew", models.BooleanField(default=True)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PAID", "Paid"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="activity",
            options={"ordering": ["-created_at"], "verbose_name_plural": "Activities"},
        ),
        migrations.AlterModelOptions(
            name="agent",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="aiinsight",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="amenity",
            options={"ordering": ["name"], "verbose_name_plural": "Amenities"},
        ),
        migrations.AlterModelOptions(
            name="automationlog",
            options={"ordering": ["-sent_at"]},
        ),
        migrations.AlterModelOptions(
            name="campaign",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="conversation",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.AlterModelOptions(
            name="deal",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="document",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="followup",
            options={"ordering": ["date", "time"]},
        ),
        migrations.AlterModelOptions(
            name="inquiry",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="lead",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Lead",
                "verbose_name_plural": "Leads",
            },
        ),
        migrations.AlterModelOptions(
            name="leadactivity",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="leadnote",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["created_at"]},
        ),
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="property",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Property",
                "verbose_name_plural": "Properties",
            },
        ),
        migrations.AlterModelOptions(
            name="propertyimage",
            options={"ordering": ["created_at"]},
        ),
        migrations.AlterModelOptions(
            name="sitesettings",
            options={
                "verbose_name": "Site Setting",
                "verbose_name_plural": "Site Settings",
            },
        ),
        migrations.AlterModelOptions(
            name="sitevisit",
            options={"ordering": ["-date", "-time"]},
        ),
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["order", "date", "time", "priority"]},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AlterModelOptions(
            name="wishlist",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="activity",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("LEAD_CREATED", "Lead Created"),
                    ("LEAD_UPDATED", "Lead Updated"),
                    ("DEAL_CREATED", "Deal Created"),
                    ("DEAL_CLOSED", "Deal Closed"),
                    ("FOLLOWUP_DONE", "Follow-up Done"),
                    ("TASK_CREATED", "Task Created"),
                    ("TASK_COMPLETED", "Task Completed"),
                    ("PROPERTY_ADDED", "Property Added"),
                    ("AGENT_ASSIGNED", "Agent Assigned"),
                    ("NOTE_ADDED", "Note Added"),
                    ("STATUS_CHANGED", "Status Changed"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="lead",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lead_activities",
                to="core.lead",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="activity",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="commission_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=2.0,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="rating",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="total_sales",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=15
            ),
        ),
        migrations.AddField(
            model_name="aiinsight",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aiinsight",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="aiinsight",
            name="recommendations",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="amenity",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="amenity",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="automationlog",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="automationlog",
            name="retry_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="campaign",
            name="bounced",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="campaign",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="created_by",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaigns",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="campaign",
            name="scheduled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="subject",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="target_audience",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="campaign",
            name="unsubscribed",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="campaign",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="conversation",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="conversation",
            name="last_message_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="conversation",
            name="lead_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="conversation",
            name="source",
            field=models.CharField(default="Website", max_length=50),
        ),
        migrations.AddField(
            model_name="conversation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="deal",
            name="client_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="deal",
            name="client_phone",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="deal",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deal",
            name="commission_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="deal",
            name="expected_close_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deal",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deal",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="document",
            name="download_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="document",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="document",
            name="mime_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="document",
            name="related_lead",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="core.lead",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="related_property",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="core.property",
            ),
        ),
        migrations.AddField(
            model_name="dripsequence",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dripsequence",
            name="template_subject",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="escalationrule",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="followup",
            name="followup_type",
            field=models.CharField(
                choices=[
                    ("CALL", "Phone Call"),
                    ("EMAIL", "Email"),
                    ("WHATSAPP", "WhatsApp"),
                    ("SMS", "SMS"),
                    ("MEETING", "Meeting"),
                    ("SITE_VISIT", "Site Visit"),
                ],
                default="CALL",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="followup",
            name="next_followup_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="followup",
            name="outcome",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="followup",
            name="reminder_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lead",
            name="budget_max",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="budget_min",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="preferred_location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="leadactivity",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("UPDATED", "Updated"),
                    ("FOLLOWUP", "Follow-up"),
                    ("DEAL", "Deal"),
                    ("NOTE", "Note"),
                    ("STATUS", "Status Change"),
                    ("ASSIGNED", "Assigned"),
                    ("CALL", "Call"),
                    ("EMAIL", "Email"),
                    ("WHATSAPP", "WhatsApp"),
                    ("MEETING", "Meeting"),
                ],
                default="UPDATED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="leadactivity",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_activities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="leadactivity",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="leadnote",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notes_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="leadnote",
            name="is_important",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="leadscore",
            name="factors",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="leadscore",
            name="predicted_conversion",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="file_attachment",
            field=models.FileField(blank=True, null=True, upload_to="chat_files/"),
        ),
        migrations.AddField(
            model_name="message",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("TEXT", "Text"),
                    ("IMAGE", "Image"),
                    ("FILE", "File"),
                    ("SYSTEM", "System"),
                ],
                default="TEXT",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="action_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="icon",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="recipient",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="pincode",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="property",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="propertyimage",
            name="caption",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="propertyimage",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="facebook_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="favicon",
            field=models.ImageField(blank=True, null=True, upload_to="site/"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="instagram_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="linkedin_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="site/"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="twitter_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="whatsapp_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="sitevisit",
            name="feedback",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sitevisit",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sitevisit",
            name="rating",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="sitevisit",
            name="reminder_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sitevisit",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="task",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_tasks",
                to="core.agent",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="task",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="reminder_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="last_active",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="wishlist",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="agent",
            name="builders",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"role": "builder"},
                related_name="builder_agents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="agent",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="agent",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="aiinsight",
            name="score",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="aiinsight",
            name="type",
            field=models.CharField(
                choices=[
                    ("lead", "Lead"),
                    ("revenue", "Revenue"),
                    ("risk", "Risk"),
                    ("market", "Market"),
                    ("performance", "Performance"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="amenity",
            name="icon",
            field=models.CharField(
                help_text="Font Awesome or Material Icon class name", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="amenity",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="automationlog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("SMS_SENT", "SMS Sent"),
                    ("EMAIL_SENT", "Email Sent"),
                    ("WHATSAPP_SENT", "WhatsApp Sent"),
                    ("PUSH_SENT", "Push Notification Sent"),
                    ("MISSED_FOLLOWUP", "Missed Followup"),
                    ("ESCALATION", "Escalation"),
                    ("AUTO_MESSAGE", "Auto Message"),
                    ("FOLLOWUP_CREATED", "Followup Created"),
                    ("TASK_CREATED", "Task Created"),
                    ("LEAD_ASSIGNED", "Lead Assigned"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="automationlog",
            name="sent_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="clicked",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="conversion",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="opened",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="reach",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="sent",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("scheduled", "Scheduled"),
                    ("paused", "Paused"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="type",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("whatsapp", "WhatsApp"),
                    ("sms", "SMS"),
                    ("social", "Social Media"),
                ],
                default="email",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="lead_name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="lead_phone",
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="deal",
            name="agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deals",
                to="core.agent",
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="builder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="builder_deals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="deal",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="property_deals",
                to="core.property",
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("NEGOTIATION", "Negotiation"),
                    ("BOOKED", "Booked"),
                    ("CLOSED", "Closed"),
                    ("FAILED", "Failed"),
                    ("CANCELLED", "Cancelled"),
                ],
                db_index=True,
                default="NEW",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="category",
            field=models.CharField(
                choices=[
                    ("LEGAL", "Legal"),
                    ("SALES", "Sales"),
                    ("PROPERTY", "Property"),
                    ("PERSONAL", "Personal"),
                    ("FINANCIAL", "Financial"),
                    ("MARKETING", "Marketing"),
                ],
                db_index=True,
                default="PERSONAL",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(upload_to="documents/%Y/%m/"),
        ),
        migrations.AlterField(
            model_name="document",
            name="uploaded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="dripsequence",
            name="channel",
            field=models.CharField(
                choices=[
                    ("SMS", "SMS"),
                    ("EMAIL", "Email"),
                    ("WHATSAPP", "WhatsApp"),
                    ("PUSH", "Push Notification"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="dripsequence",
            name="delay_days",
            field=models.IntegerField(
                help_text="Days after lead creation",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="dripsequence",
            name="step_number",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="escalationrule",
            name="escalate_to",
            field=models.ForeignKey(
                limit_choices_to={"role__in": ["builder", "admin"]},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="escalated_leads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="escalationrule",
            name="missed_followups",
            field=models.IntegerField(
                default=2,
                help_text="Number of missed followups before escalation",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="followup",
            name="agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followups",
                to="core.agent",
            ),
        ),
        migrations.AlterField(
            model_name="followup",
            name="date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="followup",
            name="lead",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followups",
                to="core.lead",
            ),
        ),
        migrations.AlterField(
            model_name="followup",
            name="sequence_step",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="followup",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("DONE", "Done"),
                    ("MISSED", "Missed"),
                    ("ESCALATED", "Escalated"),
                    ("CANCELLED", "Cancelled"),
                ],
                db_index=True,
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inquiries_handled",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="email",
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inquiries",
                to="core.property",
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leads",
                to="core.agent",
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="builder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="builder_leads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="lead",
            name="email",
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="lead",
            name="escalation_level",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(2),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="followup_count",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="lead",
            name="phone",
            field=models.CharField(
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="priority",
            field=models.CharField(
                choices=[("HOT", "Hot"), ("WARM", "Warm"), ("COLD", "Cold")],
                db_index=True,
                default="WARM",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="source",
            field=models.CharField(db_index=True, default="Website", max_length=50),
        ),
        migrations.AlterField(
            model_name="lead",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("CONTACTED", "Contacted"),
                    ("VISIT", "Site Visit"),
                    ("NEGOTIATION", "Negotiation"),
                    ("CLOSED", "Closed"),
                    ("FAILED", "Failed"),
                    ("HOT", "Hot"),
                    ("WARM", "Warm"),
                    ("COLD", "Cold"),
                ],
                db_index=True,
                default="NEW",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="leadactivity",
            name="lead",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activity_logs",
                to="core.lead",
            ),
        ),
        migrations.AlterField(
            model_name="leadnote",
            name="lead",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lead_notes",
                to="core.lead",
            ),
        ),
        migrations.AlterField(
            model_name="leadscore",
            name="intent_level",
            field=models.CharField(
                choices=[("HIGH", "High"), ("MEDIUM", "Medium"), ("LOW", "Low")],
                default="MEDIUM",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="leadscore",
            name="lead",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="score",
                to="core.lead",
            ),
        ),
        migrations.AlterField(
            model_name="leadscore",
            name="score",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages_sent",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="is_read",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("lead", "Lead"),
                    ("message", "Message"),
                    ("task", "Task"),
                    ("document", "Document"),
                    ("system", "System"),
                    ("deal", "Deal"),
                    ("followup", "Follow-up"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="baths",
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="beds",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="location",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="property",
            name="project_name",
            field=models.CharField(
                blank=True, db_index=True, max_length=200, null=True
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("Flat", "Flat"),
                    ("Villa", "Villa"),
                    ("Bungalow", "Bungalow"),
                    ("Duplex", "Duplex"),
                    ("Penthouse", "Penthouse"),
                    ("Office", "Office"),
                    ("Shop", "Shop"),
                    ("Showroom", "Showroom"),
                    ("Warehouse", "Warehouse"),
                    ("Land", "Land"),
                    ("Plot", "Plot"),
                    ("Plots", "Plots"),
                    ("Farmhouse", "Farmhouse"),
                    ("Industrial", "Industrial"),
                ],
                db_index=True,
                default="Flat",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="sqft",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="status",
            field=models.CharField(
                choices=[
                    ("Available", "Available"),
                    ("Sold Out", "Sold Out"),
                    ("Coming Soon", "Coming Soon"),
                    ("Under Construction", "Under Construction"),
                ],
                db_index=True,
                default="Available",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="title",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="phone",
            field=models.CharField(
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="sitevisit",
            name="builder",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="site_visits",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="sitevisit",
            name="date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="sitevisit",
            name="lead",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="site_visits",
                to="core.lead",
            ),
        ),
        migrations.AlterField(
            model_name="sitevisit",
            name="property",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="site_visits",
                to="core.property",
            ),
        ),
        migrations.AlterField(
            model_name="sitevisit",
            name="status",
            field=models.CharField(
                choices=[
                    ("SCHEDULED", "Scheduled"),
                    ("CONFIRMED", "Confirmed"),
                    ("DONE", "Done"),
                    ("CANCELLED", "Cancelled"),
                    ("RESCHEDULED", "Rescheduled"),
                    ("NO_SHOW", "No Show"),
                ],
                db_index=True,
                default="SCHEDULED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="lead",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="core.lead",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("IN_PROGRESS", "In Progress"),
                    ("DONE", "Done"),
                    ("CANCELLED", "Cancelled"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("builder", "Builder"),
                    ("agent", "Agent"),
                    ("user", "User"),
                    ("admin", "Admin"),
                ],
                db_index=True,
                default="user",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wishlisted_by",
                to="core.property",
            ),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wishlist",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["user", "created_at"], name="core_activi_user_id_5648ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["activity_type"], name="core_activi_activit_8c287a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(fields=["lead"], name="core_activi_lead_id_785b63_idx"),
        ),
        migrations.AddIndex(
            model_name="agent",
            index=models.Index(
                fields=["is_active"], name="core_agent_is_acti_f8b8b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agent",
            index=models.Index(
                fields=["created_at"], name="core_agent_created_fae941_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiinsight",
            index=models.Index(
                fields=["type", "is_active"], name="core_aiinsi_type_862a12_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="automationlog",
            index=models.Index(
                fields=["lead", "action_type"], name="core_automa_lead_id_88a079_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="automationlog",
            index=models.Index(
                fields=["status", "sent_at"], name="core_automa_status_2f29cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["created_by", "status"], name="core_campai_created_d7e04c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["status", "scheduled_at"], name="core_campai_status_c5cf2d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["type", "status"], name="core_campai_type_d63ca3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["lead_phone"], name="core_conver_lead_ph_5fa1da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["is_active", "updated_at"],
                name="core_conver_is_acti_0a0d4d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(
                fields=["builder", "status"], name="core_deal_builder_7afa72_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(
                fields=["agent", "status"], name="core_deal_agent_i_c897c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(
                fields=["status", "created_at"], name="core_deal_status_ca9ee7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(fields=["lead"], name="core_deal_lead_id_8783f7_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["uploaded_by", "category"],
                name="core_docume_uploade_2959b5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["category", "created_at"], name="core_docume_categor_82b34b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dripsequence",
            index=models.Index(
                fields=["builder", "is_active"], name="core_dripse_builder_1e07ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="escalationrule",
            index=models.Index(
                fields=["builder", "is_active"], name="core_escala_builder_aedd26_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="followup",
            index=models.Index(
                fields=["agent", "date", "status"],
                name="core_follow_agent_i_68e71f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="followup",
            index=models.Index(
                fields=["lead", "status"], name="core_follow_lead_id_e81626_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="followup",
            index=models.Index(
                fields=["status", "date"], name="core_follow_status_1cd8b4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inquiry",
            index=models.Index(
                fields=["property", "created_at"], name="core_inquir_propert_a5adc0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inquiry",
            index=models.Index(
                fields=["is_read", "created_at"], name="core_inquir_is_read_454f84_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["builder", "status"], name="core_lead_builder_f7e60e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["builder", "created_at"], name="core_lead_builder_5454a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["assigned_to", "status"], name="core_lead_assigne_30d8a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["priority", "status"], name="core_lead_priorit_35f17d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["source"], name="core_lead_source_e0b43c_idx"),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["status", "created_at"], name="core_lead_status_a96776_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["email"], name="core_lead_email_40e23f_idx"),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["phone"], name="core_lead_phone_c7deab_idx"),
        ),
        migrations.AddIndex(
            model_name="leadactivity",
            index=models.Index(
                fields=["lead", "created_at"], name="core_leadac_lead_id_188955_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leadactivity",
            index=models.Index(
                fields=["activity_type"], name="core_leadac_activit_610e7b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leadnote",
            index=models.Index(
                fields=["lead", "created_at"], name="core_leadno_lead_id_1ad31f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leadscore",
            index=models.Index(fields=["score"], name="core_leadsc_score_69cb79_idx"),
        ),
        migrations.AddIndex(
            model_name="leadscore",
            index=models.Index(
                fields=["intent_level"], name="core_leadsc_intent__bf2d8a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation", "created_at"],
                name="core_messag_convers_d2b392_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["is_read"], name="core_messag_is_read_b327c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "is_read"], name="core_notifi_recipie_aeffaf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["type", "created_at"], name="core_notifi_type_82fbc5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(fields=["user"], name="core_profil_user_id_155486_idx"),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["builder", "status"], name="core_proper_builder_1ff8c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["location", "property_type"],
                name="core_proper_locatio_a40157_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["project_name"], name="core_proper_project_a9804b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["status", "created_at"], name="core_proper_status_771220_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["property_type", "status"],
                name="core_proper_propert_92cd34_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sitevisit",
            index=models.Index(
                fields=["agent", "date", "status"],
                name="core_sitevi_agent_i_305551_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sitevisit",
            index=models.Index(
                fields=["builder", "status"], name="core_sitevi_builder_c6d195_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sitevisit",
            index=models.Index(fields=["lead"], name="core_sitevi_lead_id_db5d80_idx"),
        ),
        migrations.AddIndex(
            model_name="sitevisit",
            index=models.Index(
                fields=["date", "status"], name="core_sitevi_date_3c09f2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["user", "status"], name="core_task_user_id_0440f1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["date", "status"], name="core_task_date_5944ab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["assigned_to", "status"], name="core_task_assigne_5bfa1c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["lead", "status"], name="core_task_lead_id_63fe6b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["role", "is_active"], name="core_user_role_f6ec93_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="core_user_email_38052c_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["username"], name="core_user_usernam_e8adca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wishlist",
            index=models.Index(
                fields=["user", "created_at"], name="core_wishli_user_id_a3e578_idx"
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="propertyinquiry",
            name="lead",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="property_inquiries",
                to="core.lead",
            ),
        ),
        migrations.AddField(
            model_name="propertyinquiry",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="property_inquiries",
                to="core.property",
            ),
        ),
        migrations.AddField(
            model_name="savedproperty",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_by",
                to="core.property",
            ),
        ),
        migrations.AddField(
            model_name="savedproperty",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_properties",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.subscriptionplan",
            ),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscription",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["user", "timestamp"], name="core_auditl_user_id_7b678c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["action", "timestamp"], name="core_auditl_action_096de0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["model_name", "timestamp"],
                name="core_auditl_model_n_078933_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="propertyinquiry",
            unique_together={("property", "lead")},
        ),
        migrations.AlterUniqueTogether(
            name="savedproperty",
            unique_together={("user", "property")},
        ),
        migrations.AddIndex(
            model_name="usersubscription",
            index=models.Index(
                fields=["user", "is_active"], name="core_usersu_user_id_568b1a_idx"
            ),
        ),
    ]
