# Generated by Django 5.2.10 on 2026-06-22 05:41

import cloudinary.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0054_auditlog_propertyinquiry_savedproperty_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="amount_unit",
            field=models.CharField(
                choices=[("L", "Lakh"), ("Cr", "Crore")], default="L", max_length=2
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="price_unit",
            field=models.CharField(
                choices=[("L", "Lakh"), ("Cr", "Crore")], default="L", max_length=2
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="lead",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lead_activities",
                to="core.lead",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="baths",
            field=models.FloatField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="sqft",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="thumbnail",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
