# Generated by Django 5.2.10 on 2026-06-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0055_deal_amount_unit_property_price_unit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="scheduler_enabled",
            field=models.BooleanField(
                default=True, help_text="Agent can toggle their scheduler"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="enable_scheduler",
            field=models.BooleanField(default=True, help_text="Enable agent scheduler"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="enable_site_visits",
            field=models.BooleanField(
                default=True, help_text="Enable site visits page"
            ),
        ),
    ]
