# Generated by Django 5.2.10 on 2026-07-02 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0056_agent_scheduler_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=11, null=True
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("CONTACTED", "Contacted"),
                    ("VISIT", "Site Visit"),
                    ("NEGOTIATION", "Negotiation"),
                    ("CLOSED", "Closed"),
                    ("FAILED", "Failed"),
                ],
                db_index=True,
                default="NEW",
                max_length=20,
            ),
        ),
    ]
