# Generated by Django 5.2.10 on 2026-07-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0057_property_latitude_property_longitude_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["latitude", "longitude"], name="core_proper_latitud_67d4ff_idx"
            ),
        ),
    ]
