# Generated by Django 5.2.10 on 2026-07-02 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0058_property_core_proper_latitud_67d4ff_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquiry",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Agar user login karke inquiry dala tha toh yaha link hota hai",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="my_inquiries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
