# Generated by Django 5.2.10 on 2026-07-03 10:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0059_inquiry_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="brochure",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="raw"
            ),
        ),
    ]
