# Generated by Django 5.2.10 on 2026-07-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0060_alter_property_brochure"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="project_video_url",
            field=models.URLField(
                blank=True,
                help_text="YouTube (ya kisi bhi) video ka link - file upload ki jagah use kar sakte ho, especially bade/detailed videos ke liye",
                max_length=500,
                null=True,
            ),
        ),
    ]
