# Generated by Django 5.2.10 on 2026-07-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0062_usersubscription_current_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubscription",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
