# Generated by Django 4.2.7 on 2026-07-14 17:00

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0064_advertisement"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Khaali chhodo — title se auto-generate ho jayega. URL me yehi dikhega: /blog/is-slug-me/",
                        max_length=220,
                        unique=True,
                    ),
                ),
                (
                    "featured_image",
                    cloudinary.models.CloudinaryField(
                        blank=True,
                        help_text="Blog list aur detail page ke top pe dikhta hai. Bina image ke bhi save ho sakta hai.",
                        max_length=255,
                        null=True,
                        verbose_name="image",
                    ),
                ),
                (
                    "excerpt",
                    models.CharField(
                        help_text="1-2 line ka summary — blog list card pe dikhta hai, aur meta description na diya ho to wahi use hota hai.",
                        max_length=300,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Poora blog content. Basic HTML allowed hai jaise <p>, <h2>, <h3>, <b>, <ul><li>, <a href=''>."
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        help_text="Google search result me ye line dikhti hai (max 160 characters). Khaali chhodo to excerpt use ho jayega.",
                        max_length=160,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=10,
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Blog list page ke top/highlighted spot me dikhega",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Status 'Published' karne par khud-ba-khud set ho jata hai, agar khaali ho",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blog_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog Post",
                "verbose_name_plural": "Blog Posts",
                "ordering": ["-published_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "published_at"],
                        name="core_blogpo_status_cfd0fd_idx",
                    ),
                    models.Index(fields=["slug"], name="core_blogpo_slug_36a1f7_idx"),
                ],
            },
        ),
    ]
