# Generated by Django 4.2.7 on 2026-07-17 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0065_blogpost"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BlogPost",
        ),
    ]
