# Generated by Django 4.2.7 on 2026-07-22 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0066_delete_blogpost"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="slug",
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
