# Generated by Django 4.2.7 on 2026-07-29 06:14

import cloudinary.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0067_property_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="FloorPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unit_type",
                    models.CharField(
                        help_text="e.g. 3 BHK, 4 BHK Penthouse", max_length=100
                    ),
                ),
                (
                    "carpet_area",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Carpet area in sq.ft",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "super_area",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Super built-up area in sq.ft",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Price in Rupees for this unit type",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "image",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="image"
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="floor_plans",
                        to="core.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "Floor Plan",
                "verbose_name_plural": "Floor Plans",
                "ordering": ["display_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="PropertyReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reviewer_name", models.CharField(max_length=100)),
                (
                    "reviewer_type",
                    models.CharField(
                        choices=[
                            ("Owner", "Owner"),
                            ("Tenant", "Tenant"),
                            ("Visitor", "Visitor"),
                            ("Others", "Others"),
                        ],
                        default="Owner",
                        max_length=20,
                    ),
                ),
                (
                    "connectivity_rating",
                    models.PositiveSmallIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "neighbourhood_rating",
                    models.PositiveSmallIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "safety_rating",
                    models.PositiveSmallIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "livability_rating",
                    models.PositiveSmallIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "good_things",
                    models.TextField(blank=True, help_text="Good things here"),
                ),
                (
                    "needs_improvement",
                    models.TextField(blank=True, help_text="Things need improvement"),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Sirf approved reviews public page par dikhengi",
                    ),
                ),
                ("helpful_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="core.property",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="property_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Property Review",
                "verbose_name_plural": "Property Reviews",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["property", "is_approved"],
                        name="core_proper_propert_a40448_idx",
                    )
                ],
            },
        ),
    ]
