# Generated by Django 4.2.7 on 2026-07-31 07:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0068_floorplan_propertyreview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="project_video",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="video"
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="video",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="video"
            ),
        ),
    ]
