# Generated by Django 4.2.7 on 2026-08-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0069_alter_property_project_video_alter_property_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="beds",
            field=models.CharField(
                blank=True, help_text="e.g. 3 or 4/5", max_length=20, null=True
            ),
        ),
    ]
