# Generated by Django 5.2.10 on 2026-08-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_alter_property_beds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(db_index=True, default='Flat', help_text="Multiple types ko comma (,) se separate karke store kiya jaata hai, e.g. 'Flat,Penthouse'", max_length=255),
        ),
    ]
