# Generated by Django 5.2.10 on 2026-09-30 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_alter_property_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('builder', 'Builder'), ('agent', 'Agent'), ('user', 'User'), ('admin', 'Admin'), ('manager', 'Manager')], db_index=True, default='user', max_length=10),
        ),
    ]
