from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import render

urlpatterns = [
    
    path('properties/', views.property_list, name='property_list'),
    #Spath('properties/', views.properties_view),
    path('properties/<int:id>/', views.property_detail, name='property_detail'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path("login/", views.login_view, name="login"),
    path("register/", views.register_view, name="register"),

    path("builder/dashboard/", views.builder_dashboard, name="builder_dashboard"),
    path("agent/dashboard/", views.agent_dashboard, name="agent_dashboard"),
    path("", views.home, name="user_home"),
    path("forgot_password/", views.forgot_password, name="forgot_password"),
    path("otp_verification/", views.otp_verification, name="otp_verification"),
    path("reset_password/", views.reset_password, name="reset_password"),
    path("profile/", views.profile, name="profile"),
    path("logout/", views.logout_view, name="logout"),
    path("edit-profile/", views.edit_profile, name="edit_profile"),
    path("my-properties/", views.my_properties, name="my_property"),
    path("my-inquiries/", views.my_inquiries, name="my_inquiries"),
    path('add-property/', views.add_property, name='add_property'),
    path('builder-dashboard/', views.builder_dashboard, name='builder_dashboard'),
    path('builder/properties/', views.property_management, name='property_management'),
    path('builder/leads/', views.lead_management, name='lead_management'),
    
   
    path('builder/leads/add/', views.add_lead, name='add_lead'),
    path('builder/leads/edit/<int:id>/', views.edit_lead, name='edit_lead'),
    
    path('export-leads/', views.export_leads, name='export_leads'),
    path('add-to-cart/<int:id>/', views.add_to_cart, name='add_to_cart'),
    path('builder/property/<int:id>/', views.builder_property_detail, name='builder_property_detail'),
    path('builder/property/delete/<int:id>/', views.delete_property, name='delete_property'),
    path('assign-property/', views.assign_property, name='assign_property'),
    path('builder/', views.builder_root),
    path('builder/create-agent/', views.create_agent, name='create_agent'),
    path('builder/agents/', views.create_agent, name='create_agent'),
    path('builder/pipeline/', views.pipeline, name='pipeline'),
    path('builder/update-lead-status/', views.update_lead_status, name='update_lead_status'),
    path('builder/lead/<int:id>/', views.lead_detail_api, name='lead_detail_api'),
    path('add-note/', views.add_note, name='add_note'),
    path('builder/analytics/', views.analytics, name='analytics'),
    path('builder/documents/', views.document_management, name='document_management'),
    path('delete-document/<int:doc_id>/', views.delete_document, name='delete_document'),
    path('builder/communication/', views.communication, name='communication'),
    path('send-message/', views.send_message, name='send_message'),
    path('client/send-message/', views.client_send_message),
    path('chatbot/', lambda request: render(request, "chatbot.html")),
    path('get-messages/', views.get_messages),
    path('agent/send-message/', views.agent_send_message),
    path('builder/create-task/', views.create_task),
    path('builder/task-done/<int:id>/', views.task_done),
    path('builder/scheduler/', views.scheduler_overview, name='scheduler'),
    path('builder/reorder-task/', views.reorder_task),
    path('builder/check-reminders/', views.check_reminders),
    path('builder/notifications/', views.notifications_page, name='notifications'),
    path('mark-notification/<int:id>/', views.mark_notification_read),
    path('builder/agent/<int:id>/', views.agent_detail, name='agent_detail'),
    path('builder/export-agents/', views.export_agents),
    path('builder/ai-insights/', views.ai_insights, name='ai_insights'),      
    path('builder/marketing/', views.marketing_automation, name='marketing_automation'),
    path('builder/campaign/create/', views.create_campaign, name='create_campaign'),
    path('builder/campaign/run/<int:id>/', views.run_campaign, name='run_campaign'),
    path('builder/campaign/delete/<int:id>/', views.delete_campaign, name='delete_campaign'),
    path('builder/users/', views.manage_users, name='manage_users'),
    path('builder/users/create/', views.create_agent, name='create_agent'),
    path('builder/users/delete/<int:id>/', views.delete_agent, name='delete_agent'),
    path('builder/users/toggle/<int:id>/', views.toggle_agent, name='toggle_agent'),
    path('agent-leads/', views.agent_leads, name='agent_leads'), 
    path('agent-properties/', views.agent_properties, name='agent_properties'),
    path('agent-profile/', views.agent_profile, name='agent_profile'),
    path('scheduler/', views.scheduler, name='scheduler'),   
    
path('builder/lead/delete/<int:id>/', views.delete_lead, name='delete_lead'),
path('agent/site-visits/', views.site_visits, name='site_visits'),
path('settings/', views.settings_view, name='settings'),
path('privacy/', views.privacy, name='privacy'),
path('delete-lead/<int:id>/', views.delete_lead, name='delete_lead'),
path('builder/export-leads/', views.export_leads_csv, name='export_leads_csv'),
path('add-deal/', views.add_deal, name='add_deal'),
path('update-deal/<int:deal_id>/', views.update_deal, name='update_deal'),
path("followup/done/<int:id>/", views.mark_followup_done, name="mark_followup_done"),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)