# Generated by Django 5.2.10 on 2026-09-21 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowcaseViewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, help_text="Page par 'Welcome, ...' me dikhega. Khali chhod sakte ho.", max_length=100, verbose_name='Dikhane wala naam (optional)')),
                ('heading', models.CharField(default='Leads Overview', max_length=120, verbose_name='Page heading')),
                ('is_active', models.BooleanField(default=True, help_text='Band karoge to login karne par kuch nahi dikhega.', verbose_name='Active')),
                ('total_leads', models.PositiveIntegerField(default=0, verbose_name='Total leads')),
                ('new_leads', models.PositiveIntegerField(blank=True, null=True, verbose_name='New')),
                ('contacted_leads', models.PositiveIntegerField(blank=True, null=True, verbose_name='Contacted')),
                ('site_visit_leads', models.PositiveIntegerField(blank=True, null=True, verbose_name='Site visit')),
                ('negotiation_leads', models.PositiveIntegerField(blank=True, null=True, verbose_name='Negotiation')),
                ('closed_leads', models.PositiveIntegerField(blank=True, null=True, verbose_name='Closed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='showcase_viewer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lead viewer (numbers only)',
                'verbose_name_plural': 'Lead viewers (numbers only)',
            },
        ),
    ]
