# Generated by Django 5.2.10 on 2026-07-08 08:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CouponCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Uppercase, no spaces. E.g., BUILDER50",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Internal note about this coupon"
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage (%)"),
                            ("fixed", "Fixed Amount (Rs.)"),
                        ],
                        default="percentage",
                        max_length=10,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage (e.g., 20 for 20%) or Fixed amount (e.g., 500 for Rs.500)",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        default=0, help_text="0 = unlimited uses"
                    ),
                ),
                ("used_count", models.PositiveIntegerField(default=0)),
                (
                    "max_uses_per_user",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="How many times one user can use this coupon",
                    ),
                ),
                ("valid_from", models.DateTimeField()),
                ("valid_until", models.DateTimeField()),
                (
                    "applicable_plan_types",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated: builder,agent. Leave empty for all",
                        max_length=20,
                    ),
                ),
                (
                    "min_order_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "plan_type",
                    models.CharField(
                        choices=[("builder", "Builder"), ("agent", "Agent")],
                        default="builder",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "price_monthly",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "price_yearly",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("max_properties", models.PositiveIntegerField(default=10)),
                ("max_agents", models.PositiveIntegerField(default=5)),
                ("max_leads", models.PositiveIntegerField(default=100)),
                (
                    "features",
                    models.JSONField(
                        blank=True, default=list, help_text="List of feature flags"
                    ),
                ),
                (
                    "razorpay_plan_id_monthly",
                    models.CharField(
                        blank=True,
                        help_text="Auto-generated Razorpay plan ID for monthly",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "razorpay_plan_id_yearly",
                    models.CharField(
                        blank=True,
                        help_text="Auto-generated Razorpay plan ID for yearly",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_popular",
                    models.BooleanField(
                        default=False, help_text="Highlight this plan as popular"
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order in which plans are displayed"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_order", "price_monthly"],
                "indexes": [
                    models.Index(
                        fields=["plan_type", "is_active"],
                        name="subscriptio_plan_ty_21d135_idx",
                    ),
                    models.Index(
                        fields=["is_active", "display_order"],
                        name="subscriptio_is_acti_c2a27e_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RazorpayOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "razorpay_order_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "razorpay_payment_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("razorpay_signature", models.TextField(blank=True, null=True)),
                (
                    "original_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("final_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                        default="monthly",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("attempted", "Attempted"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                ("subscription_start", models.DateField(blank=True, null=True)),
                ("subscription_end", models.DateField(blank=True, null=True)),
                ("notes", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "coupon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="subscriptions.couponcode",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="razorpay_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subscriptions.subscriptionplan",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="couponcode",
            name="applicable_plans",
            field=models.ManyToManyField(
                blank=True,
                help_text="Leave empty to apply to all plans",
                related_name="coupons",
                to="subscriptions.subscriptionplan",
            ),
        ),
        migrations.CreateModel(
            name="CouponUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("used_at", models.DateTimeField(auto_now_add=True)),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usages",
                        to="subscriptions.couponcode",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="subscriptions.razorpayorder",
                    ),
                ),
            ],
            options={
                "unique_together": {("coupon", "user", "order")},
            },
        ),
        migrations.AddIndex(
            model_name="razorpayorder",
            index=models.Index(
                fields=["user", "status"], name="subscriptio_user_id_eb0bb8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="razorpayorder",
            index=models.Index(
                fields=["razorpay_order_id"], name="subscriptio_razorpa_30a114_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="couponcode",
            index=models.Index(
                fields=["code", "is_active"], name="subscriptio_code_55cd1e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="couponcode",
            index=models.Index(
                fields=["valid_from", "valid_until"],
                name="subscriptio_valid_f_bbf786_idx",
            ),
        ),
    ]
